'use strict';

App.constant('LENGTH_CONFIG', {
    AGENCY_NAME_MAX: 18,
    AGENCY_NAME_MIN: 4,

    REVIEW_TITLE_MAX: 25,
    REVIEW_TITLE_MIN: 4,
    REVIEW_SHORT: 70,
    REVIEW_MIN_WORDS: 10,
    REVIEW_DESCRIPTION: 400,

    COMMENT_REVIEW_MIN_WORDS: 10,
    COMMENT_REVIEW_CONTENT: 400,

    NEWS_SHORT: 200
});